### ISSUE TITLE
uninstallable

### ISSUE THREAD

**Issue by NeoVance** [preprocess/pre-phpx#1]
Using version ^0.2.0 for pre/phpx
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - pre/plugin 0.7.7 requires composer-plugin-api ^1.1 -> no matching package found.
    - pre/phpx 0.2.0 requires pre/plugin ^0.7.7 -> satisfiable by pre/plugin[0.7.7].
    - Installation request for pre/phpx ^0.2.0 -> satisfiable by pre/phpx[0.2.0].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by assertchris** [comment]
Sorry for the delayed response - only saw this now. About to tag a new version, so I'll test with that...

**Comment by assertchris** [comment]
@NeoVance Version 0.3.0 installs and works fine for me. Lemme know if you have any issues with that...
